### ISSUE TITLE
Connection Time Out after few seconds of connect attempt

### ISSUE THREAD

**Issue by gdeiorio** [KoenLav/cordova-plugin-chrome-apps-sockets-tcp#13]
Hello,
I've tried this plugin with several Android devices and it always worked perfectly.
While using it with a Xiaomi Mi A2 Lite, it gives result -104 on the connect method and throws a "Connection timed out" error.
Why this difference among devices?
Is there something I can do to increase the connection timeout limit?
Thanks.

**Comment by KoenLav** [comment]
@gdeiorio as I don't have an Android 9 device handy for a reproduction, I'd suggest forking this package and looking at the connect or finishConnect functions in the code where you can see the following:

```
        } catch (IOException e) {
          callbackContext.error(buildErrorInfo(-104, e.getMessage()));
        }
```

The -104 indicates something went wrong in the connection process and the message indicates a timeout was the source of the issue.

Does it never work? Or only when the connection takes a lot of time?

This might also help:
https://stackoverflow.com/questions/5632279/how-to-set-timeout-on-client-socket-connection

**Comment by gdeiorio** [comment]
It turned out it was not an Android 9 related issues, since other devices with that version are not giving trouble.
Actually, the issue happens, most of the times, after a really short time, like 200 or 300ms.
Another strange is behaviour is that the device can connect to the socket via TCP Telnet Terminal, it just can't connect via app.
Am I missing some permissions (but, if so, I don't get why other devices have no problems)?

**Comment by KoenLav** [comment]
Some links which might be relevant:

https://stackoverflow.com/questions/6586443/android-tcp-permission-denied-error
https://stackoverflow.com/questions/53081049/local-socket-access-denied-in-api23-working-in-api21

In some other blog I read about these two permissions:

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"></uses-permission>
<uses-permission android:name="android.permission.INTERNET"></uses-permission>

**Comment by gdeiorio** [comment]
Hi, 
Looks like the problem is solved.
Apparently it happens when there are both wifi and 4g connection on, some new devices switch automatically to the 4g if the wifi net hasn't access to internet or it has a low quality connection.
Since the device needed to be connected to a specific wifi net, turning off the 4g connection worked.
