### ISSUE TITLE
Issues w/ Ionic 3

### ISSUE THREAD

**Issue by rustygreen** [KoenLav/cordova-plugin-chrome-apps-sockets-tcp#9]
I'm unable to get this plugin to work in Ionic 3. I'm doing the following steps:

```
// 1) Add plugin.
cordova plugin add cordova-plugin-chrome-apps-sockets-tcp

// 2) Use the plugin.
    this.platform.ready()
      .then((readySource) => {
        if (readySource == 'cordova') {
          // This will throw an error (chrome is undefined)
          (<any>window).chrome.tcp.socket.create();
        }
      });
```

I get "chrome" is not defined. Any suggestions?

**Comment by KoenLav** [comment]
I have little experience with Ionic.

I see in your forked repo you already managed to figure it out?

**Comment by rustygreen** [comment]
@KoenLav, it turns out that the problem was with IonicView - not the plugin. I didn't realize that IonicView only supports certain plugins: https://forum.ionicframework.com/t/tcp-requests-in-ionic-3/121490/12.
